/*
 * MIDI State Machine of Simple Stupid Synthesizer
 *
 * Copyright (C) 2023 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint>
 *
 * Author's web site: www.juergen-reuter.de
 */

#include "midi-state-machine.hpp"
#include <math.h>
#include "pico/stdlib.h"
#include "bsp/board.h"

const double
MIDI_state_machine::OCTAVE_FREQ_RATIO = 2.0;

const uint8_t
MIDI_state_machine::NOTES_PER_OCTAVE = 12;

const double
MIDI_state_machine::A4_FREQ = 440.0;

const uint8_t
MIDI_state_machine::A4_NOTE_NUMBER = 69;

const uint8_t
MIDI_state_machine::COUNT_HEADROOM_BITS = 0x8;

const uint32_t
MIDI_state_machine::COUNT_INC = ((long)1u) << COUNT_HEADROOM_BITS;

MIDI_state_machine::MIDI_state_machine()
{
}

MIDI_state_machine::~MIDI_state_machine()
{
}

void
MIDI_state_machine::osc_init(const uint32_t sample_freq)
{
  const double count_inc = COUNT_INC;
  const double log_note_step_ratio = log(OCTAVE_FREQ_RATIO) / NOTES_PER_OCTAVE;
  for (size_t osc = 0; osc < NUM_OSC; osc++) {
    const double osc_freq =
      A4_FREQ * exp((osc - (double)A4_NOTE_NUMBER) * log_note_step_ratio);
    // half (0.5) inc, since square wave elongation toggles twice per period
    const uint32_t count_wrap =
      round(0.5 * count_inc * sample_freq / osc_freq);
    MIDI_state_machine::osc_status_t *osc_status = &_osc_statuses[osc];
    osc_status->count_wrap = count_wrap;
    osc_status->count = 0;
    osc_status->velocity = 0;
    osc_status->elongation = 0;
  }
}

void
MIDI_state_machine::state_init()
{
  for (size_t channel = 0; channel < NUM_CHN; channel++) {
    channel_status_t *channel_status = &_midi_status.channel_status[channel];
    for (size_t note = 0; note < NUM_OSC; note++) {
      note_status_t *note_status = &channel_status->note_status[note];
      note_status->velocity = 0;
    }
  }
}

void
MIDI_state_machine::led_init(const uint8_t gpio_pin_activity_indicator)
{
  _gpio_pin_activity_indicator = gpio_pin_activity_indicator;
  gpio_init(gpio_pin_activity_indicator);
  gpio_set_dir(gpio_pin_activity_indicator, GPIO_OUT);
}

void
MIDI_state_machine::init(const uint32_t sample_freq,
                         const uint8_t gpio_pin_activity_indicator)
{
  _timestamp_active_sensing = time_us_64();
  osc_init(sample_freq);
  state_init();
  led_init(gpio_pin_activity_indicator);
  board_init();
  tusb_init();
}

MIDI_state_machine::osc_status_t *
MIDI_state_machine::get_osc_statuses()
{
  return &_osc_statuses[0];
}

void
MIDI_state_machine::add_to_osc_status(const uint8_t pitch,
                                      const int8_t delta_velocity)
{
  osc_status_t *osc_status = &_osc_statuses[pitch];
  osc_status->velocity += delta_velocity;
  const int16_t elongation = osc_status->elongation;
  if (elongation > 0) {
    osc_status->elongation += delta_velocity;
  } else if (elongation < 0) {
    osc_status->elongation -= delta_velocity;
  } else {
    osc_status->elongation = delta_velocity;
  }
}

/*
 * For the structure of event packets, see Sect. 4, "USB-MIDI Event
 * Packets" in the "Universal Serial Bus Device Class Definition for
 * MIDI Devices" at https://usb.org/sites/default/files/midi10.pdf.
 */
void
MIDI_state_machine::consume_event_packet(const uint8_t *event_packet)
{
  const uint8_t code_index_number = event_packet[0] & 0xf;
  if (code_index_number == 0x9) {
    // note on
    const uint8_t channel = event_packet[1] & 0xf;
    const uint8_t pitch = event_packet[2] & 0x7f;
    const uint8_t velocity = event_packet[3] & 0x7f;
    channel_status_t *channel_status = &_midi_status.channel_status[channel];
    note_status_t *note_status = &channel_status->note_status[pitch];
    const uint8_t prev_velocity = note_status->velocity;
    note_status->velocity = velocity;
    add_to_osc_status(pitch, velocity - prev_velocity);
    gpio_put(_gpio_pin_activity_indicator, velocity > 0 ? 1 : 0);
  } else if (code_index_number == 0x8) {
    // note off
    const uint8_t channel = event_packet[1] & 0xf;
    const uint8_t pitch = event_packet[2] & 0x7f;
    channel_status_t *channel_status = &_midi_status.channel_status[channel];
    note_status_t *note_status = &channel_status->note_status[pitch];
    const uint8_t velocity = note_status->velocity;
    note_status->velocity = 0;
    add_to_osc_status(pitch, -velocity);
    gpio_put(_gpio_pin_activity_indicator, 0);
  }
}

void
MIDI_state_machine::rx_task()
{
  tud_task();
  if (!tud_midi_mounted()) {
    return;
  }
  while (tud_midi_available()) {
    /*
     * For the structure of the 4-byte packets, see "USB_MIDI Event
     * Packets" in: USB device class definition
     * (usb.org/sites/default/files/midi10.pdf), page 16.
     */
    uint8_t event_packet[4];
    if (tud_midi_packet_read(event_packet)) {
      consume_event_packet(&event_packet[0]);
    }
  }
}

void
MIDI_state_machine::produce_tx_data(uint8_t *buffer,
                                    __unused const size_t max_buffer_size,
                                    size_t *const buffer_size)
{
  /* when deadline for next active sensing has expired, produce a
     packet containing a sensive acting MIDI code */
  const uint64_t timestamp_now = time_us_64();
  if (timestamp_now - _timestamp_active_sensing > 300000) {
    _timestamp_active_sensing += 300000;
    buffer[0] = 0xFE; // MIDI code for active sensing
    *buffer_size = 1;
  } else {
    *buffer_size = 0;
  }
}

void
MIDI_state_machine::tx_task()
{
  static uint8_t tx_data_buffer[3];
  size_t buffer_size;
  produce_tx_data(tx_data_buffer, sizeof(tx_data_buffer), &buffer_size);
  tud_midi_stream_write(0, tx_data_buffer, buffer_size);
}

/*
 * Local variables:
 *   mode: c++
 *  coding: utf-8
 * End:
 */
