/*
 * MIDI Constants for the Simple Stupid Synthesizer
 *
 * Copyright (C) 2024 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef MIDI_CONSTANTS_HPP
#define MIDI_CONSTANTS_HPP

class Midi_constants
{
public:
  /** number of MIDI keys */
  static const uint8_t NUM_KEYS = 0x80;

  /** number of MIDI channels */
  static const uint8_t NUM_CHN = 0x10;
};

#endif /* MIDI_CONSTANTS_HPP */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
