/*
 * I2S Audio Target of Simple Stupid Synthesizer
 *
 * Copyright (C) 2023 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef SIMPLE_STUPID_SYNTH_HPP
#define SIMPLE_STUPID_SYNTH_HPP

#include <inttypes.h>
#include "midi-state-machine.hpp"
#include "audio-target.hpp"

class Simple_stupid_synth {
public:
  static const uint32_t DEFAULT_SAMPLE_FREQ; // [HZ]
  static const uint32_t GPIO_PIN_LED;
  Simple_stupid_synth(Audio_target *const audio_target,
                      MIDI_state_machine *const midi_state_machine,
                      const uint8_t gpio_pin_activity_indicator);
  void main_loop();
private:
  static const uint8_t VOL_BITS;
  Audio_target *const _audio_target;
  MIDI_state_machine *const _midi_state_machine;
  void synth_task();
};

#endif /* SIMPLE_STUPID_SYNTH_HPP */

/*
 * Local variables:
 *   mode: c++
 *  coding: utf-8
 * End:
 */
